apiVersion: v1
kind: Service
metadata:
  name: pki
  labels:
    app: pki
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: pki
  selector:
    app: pki
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pki-config
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  config.yml: |
    authorities:
    - name: ac
      certificatefile: /etc/certs/ac.pem
      privatekeyfile: /etc/certs/ac.key
---
apiVersion: v1
kind: Secret
metadata:
  name: pki-ac
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUhHVENDQlFHZ0F3SUJBZ0lJQWJJd0RIdG9teGN3RFFZSktvWklodmNOQVFFTEJRQXdnYVV4Q3pBSkJnTlYKQkFZVEFrWlNNVUV3UHdZRFZRUUtERGhVUlZOVUlFeEpUa3RaSUUxQlUxUkZVaUJGVEVWRFZGSkpRMGxVUlNCUwpSVk5GUVZVZ1JFbFRWRkpKUWxWVVNVOU9JRVpTUVU1RFJURXBNQ2NHQTFVRUN3d2dWRVZUVkNCTVNVNUxXU0JOClFWTlVSVklnTURBd01pQTBORFEyTURnME5ESXhLREFtQmdOVkJBTU1IMVJGVTFRZ1RFbE9TMWtnVFVGVFZFVlMKSUVGVlZFOVNTVlJGSUVWU1JFWXdJQmNOTVRVd01qQXlNVFUxT1RBeVdoZ1BNakEzTlRBeU1ESXhOVFU1TURKYQpNSUd1TVFzd0NRWURWUVFHRXdKR1VqRkJNRDhHQTFVRUNndzRWRVZUVkNCTVNVNUxXU0JOUVZOVVJWSWdSVXhGClExUlNTVU5KVkVVZ1VrVlRSVUZWSUVSSlUxUlNTVUpWVkVsUFRpQkdVa0ZPUTBVeEtUQW5CZ05WQkFzTUlGUkYKVTFRZ1RFbE9TMWtnVFVGVFZFVlNJREF3TURJZ05EUTBOakE0TkRReU1URXdMd1lEVlFRRERDaFVSVk5VSUV4SgpUa3RaSUUxQlUxUkZVaUJCUXlCSlRrWlNRVk5VVWxWRFZGVlNSU0JGVWtSR01JSUNJakFOQmdrcWhraUc5dzBCCkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQWpnL2syd2F3TjVIeXhFME54a1hVSC90VGJua1VENm0zY0dqWmhway8KU2E3QVRSaFNQMjhqZS9ZL3RySmpsNGhGMlErZG9IbEZ1V0FyMzIwRk9nTDNzWGdKejZrdnRlWGNMeFlXUFY2VQovQjJpd0lVcTc0ZlA5SzZKUTZrMHdBTU9QTVRwNXRIOEFUWTdOa1ovRk9RL2NOb2k2eFpzQUFPUzVCVXY0d1E2ClhocWJ1MUZ0U1krMi9KZUdkbTNTT3M0QWdtUDM1UzBkQklOVkFxcUtWNkhMcjRCSzhoTVAvUzRWRlV4MXhCY1EKMlVUanlpSlRaTXVKVVlLN0x6YlcyUWlJYVJoY0FqNTY5RUV1WEtrVHhNWVh1WVR0WTdXK2JWZkl0cUY0bXRXVwpFSnJWeGd1WmROQTdIZjVjcm1lbVlUYzFBb0NVK0hyZU1jWlBzNkZ0Tm5yT3dXc3B4WmFjcEFVMkJqOFdGWHBWCk9yZFg4akJOTU95ZTNpQ3N4SU01NUZ4OCtVR3YxLzZWR1lRUEl1R2VPZHg4ajdvTlZKanlKZm0vQnAvZmhsQzQKblNTK3dLSXVobzg4VGJLT2RLaXM4Z3ExSit1WTVzeThQVkVTV2FzSFpwVFNwOVpOTUU1U3pHOFR2amhvcFZQWAorSHJ3ckQ3VURTd25qdkpoaG9Jd0R6dGVvVDlUUldlWHUrbStlRWpYaUQzOGdXbDNta0t4THRQZFc5VEo2NHR0CmN5TXJkNGNBSGx4SW1PQU55VDVGazVqRGJKZWdNeE5RenpDZmhOZmFqaEpsSjJpZmlGYXNyMEZ6aXUwbWNvUEoKQ05zM2ovTXlGejRHL2ZEc21CRnBoRDdpaWFNQ01Ja0JJWS9GOSszdFhhNzBTekhhQ2VnaE4yS2JOSit5c3cxcwpUQXNDQXdFQUFhT0NBVDR3Z2dFNk1CMEdBMVVkRGdRV0JCUlBVVW80TGZVV2ZGREltSWVLRVRiMnlzdnJQVEFTCkJnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQU1COEdBMVVkSXdRWU1CYUFGQXYzQlE1TzNCd05YY3Y1SXI2eDArZksKVmNiK01ISUdBMVVkSUFSck1Ha3dad1lIS3dZQkJRVUhBekJjTUZvR0NDc0dBUVVGQndJQkZrNW9kSFJ3T2k4dgphV2RqTG0xaGMzUmxjaTVzYVc1cmVTNWxjbVJtTG1aeUwzQmpMM1JsYzNSZmJHbHVhM2xmYldGemRHVnlYMkZqClgybHVkR1Z5YldWa2FXRnBjbVZmWlhKa1ppNXdaR1l3WUFZRFZSMGZCRmt3VnpCVm9GT2dVWVpQYUhSMGNEb3YKTDJsbll5NXRZWE4wWlhJdWJHbHVhM2t1WlhKa1ppNW1jaTlqY213dmRHVnpkRjlzYVc1cmVWOXRZWE4wWlhKZgpZV05mYVc1MFpYSnRaV1JwWVdseVpWOWxjbVJtTG1OeWJEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0RRWUpLb1pJCmh2Y05BUUVMQlFBRGdnSUJBRFl1dVdESXJ2ZnV6emNkNXd5MDN1eDdkRnRoeUVLaDIwMXJpb3gvSFZveVFXV2UKSTI2N0x2bFBFcHAvVEhBbkJUdXR4RjdOL0ZaMmtyeUk4UmxTa0NXMmFwS2M0NzJHd3JBOGxwUzl6QndlMTlXbAp1NVZGVE9kN1dTMFNZVkVkYzRObFBkWFlNTjNwSko1NDl0MnM3ektCekRoQVZ6L2t2dEFOZ0djUEtnZGhDTnAyCldpdHQrRzR0emdkOVpER1lpMG1HL29zZmdJSExIcTRBZnRDSHd0VCtFWVJzdTlnTEFPdnJHK2IrMXk1eTFkYUsKbVFpc3k3S3pBVGdVQng5NUtkU3MvNTZUdk0xMHJuZU9uQnBpTUp4QW0zOWVHcElqYjVhSUo4Kyt2SCtVNWllbApHRXhGOXlBOXlqWEl0akViSlh0WjVqMGFSd0cyTDQ5RFMwK3hROXZPbC9HS1Vmc3B0Qnl0V0VNaGFIVUVwcW9pCjlLdXdlZVR6N3l3cUVKTFg3Y2RDQ0xHaXRnS1FxT1hkWXZ3Sk1SSWN3Mjg0Rlh2eWRTcGFSV2t4Y0ZwNFNWa1IKWjRMYktqc2taMVZnK2ZnRGpZNjdnWldqaDJONHRYOXZaUjhDZU4xMmtzdmtZUnZkTy85YWtyM3I1VjJQdis3ZQpJSGtlTUVoZ29iRmd1ckRubUs0bTd5bVVaUjdlNm1nRUk4SHgyamMwOUJSalBxbndGYy8rT1hKZmxaNGY4ZHpnCnlrdk9oMWp3Z0J5eFcvTXA1c3JrMEN2MUVvNzVjRW5iSkdOazFrbmF2YjhoWm1NQWZMZWtGbGdEeEI2RWdmaG4KWVk3V2VWSnJpdzI2ZTAxS0x0TFNXZElwMFRzam1lWFZCM2JoTjJncG50UTFZdXB5azh1T1R5OGlsakV1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS1FJQkFBS0NBZ0VBamcvazJ3YXdONUh5eEUwTnhrWFVIL3RUYm5rVUQ2bTNjR2paaHBrL1NhN0FUUmhTClAyOGplL1kvdHJKamw0aEYyUStkb0hsRnVXQXIzMjBGT2dMM3NYZ0p6Nmt2dGVYY0x4WVdQVjZVL0IyaXdJVXEKNzRmUDlLNkpRNmswd0FNT1BNVHA1dEg4QVRZN05rWi9GT1EvY05vaTZ4WnNBQU9TNUJVdjR3UTZYaHFidTFGdApTWSsyL0plR2RtM1NPczRBZ21QMzVTMGRCSU5WQXFxS1Y2SExyNEJLOGhNUC9TNFZGVXgxeEJjUTJVVGp5aUpUClpNdUpVWUs3THpiVzJRaUlhUmhjQWo1NjlFRXVYS2tUeE1ZWHVZVHRZN1crYlZmSXRxRjRtdFdXRUpyVnhndVoKZE5BN0hmNWNybWVtWVRjMUFvQ1UrSHJlTWNaUHM2RnRObnJPd1dzcHhaYWNwQVUyQmo4V0ZYcFZPcmRYOGpCTgpNT3llM2lDc3hJTTU1Rng4K1VHdjEvNlZHWVFQSXVHZU9keDhqN29OVkpqeUpmbS9CcC9maGxDNG5TUyt3S0l1CmhvODhUYktPZEtpczhncTFKK3VZNXN5OFBWRVNXYXNIWnBUU3A5Wk5NRTVTekc4VHZqaG9wVlBYK0hyd3JEN1UKRFN3bmp2Smhob0l3RHp0ZW9UOVRSV2VYdSttK2VFalhpRDM4Z1dsM21rS3hMdFBkVzlUSjY0dHRjeU1yZDRjQQpIbHhJbU9BTnlUNUZrNWpEYkplZ014TlF6ekNmaE5mYWpoSmxKMmlmaUZhc3IwRnppdTBtY29QSkNOczNqL015CkZ6NEcvZkRzbUJGcGhEN2lpYU1DTUlrQklZL0Y5KzN0WGE3MFN6SGFDZWdoTjJLYk5KK3lzdzFzVEFzQ0F3RUEKQVFLQ0FnRUFpSGNXSlp4UUxLR0RyalJDdGlNZitUVHBXV2J2OFhmYjRoeW1VTmpuWmJWN3Z0Tk5OdWhoRXRSagpNZkk5SHpSbHZIUjJ1OCtqUGNiM2ZpSHc4bUFsWmhKa2dsb0luZGhYNGRkNnQ2c2l2T2tQRFpjZXZvZ2RLUE44Cm9rVnBpY1dscUpTVUNBblE1YTBkeGk2RUp5SjNHc1pBNHNsZ0o4ZEhGTmlSYnFjQ0ZxSEMxWGNMMzYweFg0V0QKUWtLT3Y3Umg0dDk3STJocHhvc09YNGhKYXBMZTRoRUFiWGdJVlBJdWlJNHhWcE85dUtpbmxPWFNiREhsRUNyZgoreVBYMFJhVVN6aCtNaDJvNlBld1BJeWlrOVNpdDdETWhZcnhpWUhaS2k4RWR1QVR6cEdlSnllL1d1b296OUFuCllkWHBpdHVJallYTkZNQ2Fydi9NVWtjUWJWUWRSVnRJOHo5dFJ1UmVCVXBVc1RWbGRPVDBoVCtOQUVzMWV4Z1IKRVJYWmFWMzZwV2ZObjBhUlZCOW51a2ZZMW84d2c3UklyOVYyNDBOK3lSZ1VrM05oSkplQWZBTGF3OHdzbmFaTwpXQzNuT3UwM3J1NUZXWGp6QzlKTWdtL05UcUNrTXhpVmFzQldqdVk3bUxWM0ZmU3FXLzJNL3QyZXplWERoVUtTCkV5V0FMM3ZXSGlKcTZ0RUJ3VFJUMG9aQ0NQcE1CYjZTWDlpR2w0ZkgyMlV1L05xbnRXMDZjZEZWYUwrZFM0cysKS2oyOGN5OENoamFsYTVuWmdYQng0UmkvQ0RtbDZMK0hsSGlBMFBqZ2p6aHhwdkRhVnRlaU1rSENJT3ZsbmRWYwpUWXZ1ZngwRHBnOFFsYUxVdVF3Sm1UVjNUYUhhSGkzTFlNNFhnc3psUEZMTVZXNElJK2tDZ2dFQkFNU1RGWVJICjRlMW5XVEtyckJXREpDQ2VnSExNWEtBdlNqdndTYVlONUo0NHcrMlJNa2NPMXFpMVVWM2NxMVlZSDVMbGh2YWgKeElOUExTQ0JseEV0cFJBNk1Eb2phZHdvWkRYcTg0NTNMU2ZEVVNGbDdwcitIUkZjTytPUm5OTG5GNXpjc3hmTQpTU21qd1lsRkl4WFN0a3F2Y3pVVHFEajJrWDFwTWhBd2RYeWN0SUl4aW4vS3RMM2dQa3JMYkRpYnRWMUs4WTJxCm9iVGRQbFU3R1BqRXptSlYremJuaEMvU1Z6b3dRZ0RKNURQSDlqL3JIVjBUYmZYNjM5ckQ5SlpuWmtjZFhKSmQKQjZGL0Y4RFJnUXhiU3lUZU9aMnpZYm1mdzFQempxKzZUNE5xcy83TlE1dlNWTmRWbkhWQjZweFFDZHhzYnNXcQpzSFBBcFJlTkZUSllYdzhDZ2dFQkFMa0NGbGdSVWR1YXpGdTdGamswc25uNk0yb1BUTm1oVkM3Ym5aKzB6Y3hUCjlzc3hHOE44UHpQRmJMZnpyWEFHMy9PQ3VqZGtybWZMS3BEVlhNc0ZtNDRIa3Jza0lVZE43SXFDV21LZFdFL1kKS0x4dDNEQVUyK3lDOWs0c09KKzdDVHVyZG5PWitUeitYQ2FTM0hzT1RibW9pMCtkRTFqbkJycFplelpGRlVsSAo2N2hUTjVvUncvbE1XbkVmd2VBeTlOYlgya1RPdWorYWJpRjBzeXBkbUFSK3h4TVJFek9scDFteDNZdTN3aUoyCkZtNlAzMGsvYVcxWWd0NTN3UWI3ODQ1MlVVSTR6Y1BLTlRCbkhVaXhROHN3YU03TFE2dVJqcU1nOXdoMWw5VVcKWGVVMXBIUVhtZlRnQ0NGYnFJUlBoUDZ0YlBlSFdKeHRnTXArNDYycWcwVUNnZ0VBTEdtcTU5c3gwV2lUUDU2SAozOGhrWmpaSmdTWnBHd3YwTXJ5a2R5OFdZeVVpSjAreDAxb241N0FudFJSQlpjOUhldkgrMzBSSFdQK1BpNU9iCjVSYXgvNHVXRDl5bWMwWnc5Ym1pMDZKYmdtdGZyak1RaU5ZM0RSQVF1K2JQVHR0RmUzeGx2ays2aS96aW9qZ0wKcUVlV1JpT0QzUThXNTkvVm1VY21ONEFyV3o4d2pXWFNDL05waUtqY2lodVIxT3hoT3JYUEE1bjB0Ujl6a09BcwpVVEJ1RE11dVdZWlBXRnFtdUkva3FiYnpwenRiaUs5L1QrTXU2ZStIbWk3QjJTVjlkejNNQjRtYlNzS2pSRDVSCmNOQkRsdzNhYUtYNXcyMjBQUWgvU1hiSHRrSnFibnhEOVRXOVUzV1ZSdXpncS9adGMrN1B6RHMzYUwreXpUSmsKQXA3eXd3S0NBUUVBaS8yT1ZybFVUVzJHc09xUjJGdU5xVXF2V05PVy9SNWNDdERYSnArekVhZC9HU1Zoc3J2egpQd05tVHBNdWE1Um9KV1NINzU1WmNlU0RvdkF2dE5mYmFzOUVNaU1XbzFQTlpzbFlCMEswTGthTUhIaXNvaDFHCmhHSmNhYTZBY2kwZXdXM3V4VzUrNzY0d29HZUVPZ0VLd3k5THFzUmFmV3ppNUdNTkhuV0xzOVdlQWUzR0p1akcKZDM5VStFQmxmWFpSV2JnZlN1MTZkT0l2NzFUVXRYdjRxWDRjdU1xMDB1SElEZERPcVFnMDk4cVBFcjMrNFBnQQptR0xmTStNOXhrRWpmR3IrOWJMeHovTFQ2SG85NkdGcHdQZ3lkamZNVHFoblcveDNzSWo2aUp6U0U3eFJZaDd4CnVoOURSNnFKaXdSNHlCVUdYUTZtK0ViTHEyMzBiZGFXV1FLQ0FRQmtnUUZzZEk0SW14VjQ2MEZiWXh3TGJKaFUKdXdLMlBrVnRHd3Q0ZlY3SytLTlIreE1MQWpVMGo3OTJ2Uk5iLzM0MCtRM1ZwVVlXM2NzTW8wL1g5bFlPMUdILwpFaWJiOHhwclBxTU8wT3hQSnRlS2cwUXNIT3FvN0I1Q3U4TUxDZ3NaNURYUzUzT29oRkVNZlRlV2lVNStzSkJaCmFWcmhhTWhiNUtQWEpMZEErUzBFT2p6b3p2WWR3bGZ6RWppeFo1VXVBUmlXK3JwYlJYYm1rMmhubFhXYkhGZ1UKTTRJMWRmZ0p3STFVR24xNkdKa0YxVUpIeXZlbHVNY1pOZFV5M3pSbzZkVkJiT1RTRXR3SFFSMGFBQ1FwTnVPaQpZODU0U3dwNDFPQ0dJRnd5aUloejNTYjEycnZTSC9iQTN1VEdETEQ0M2ljWTJURzJCUkVoNTZyVDVMTHoKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pki
  labels:
    app: pki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pki
  template:
    metadata:
      labels:
        app: pki
    spec:
      containers:
      - name: pki
        image: zed33xg1.distribution.edf.fr:1028/pki
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: pki-config
          mountPath: /etc/pki
        - name: pki-ac
          mountPath: /etc/certs
      imagePullSecrets:
      - name: zed33xg1-1
      volumes:
      - name: pki-config
        configMap:
          name: pki-config
      - name: pki-ac
        secret:
          secretName: pki-ac
          items:
          - key: cert
            path: ac.pem
          - key: key
            path: ac.key
